
version: "3"

services:
    app:
        depends_on:
            - php
        image: nginx:1
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        tty: true
        working_dir: /var/www/html
    php:
        image: php:fpm
        volumes:
            - ./app:/var/www/html
