
version: "3"

services:
    javascript-html-sample-app:
        image: nginx:1
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        tty: true
        working_dir: /var/www/html
